### PR TITLE
implements for PeerMembershipQuery

### LINKED ISSUE #125: How to list peers that are not anchor nodes on the channel
we can list anchor peers from channel‘s ConfigBlock
but how to list other joined peers that are not anchor nodes

### PR DESCRIPTION
**Pull request by 1gezhanghao**
fix #125

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@1gezhanghao , please fix CI error.

**Comment by 1gezhanghao** [comment]
@SamYuan1990 fix commited，please make a review

**Comment by 1gezhanghao** [comment]
@SamYuan1990  the accidentally deleted file signaturepolicy.go recovered， please make a review

**Comment by 1gezhanghao** [comment]
@SamYuan1990 have tested with golangci-lint, please make a review

**Review by SamYuan1990 — APPROVED** [review]
LGTM

**Pull request merged**
