### PR TITLE
Add pipeline for auto release page creation.

### PR DESCRIPTION
**Pull request by SamYuan1990**
sample for preview https://github.com/SamYuan1990/fabric-admin-sdk/releases

```
git checkout origin main
git checkout main
git pull
git tag v0.0.0-alpha
git remote -v
git push origin v0.0.0-alpha
```

### CODE REVIEW

**Comment by SamYuan1990** [comment]
fix #76

**Review by bestbeforetoday — COMMENTED** [review]
I don't think this is a good idea. The README should provide information for people coming to the repository, not anything specific to a particular release version. The text for a GitHub release is more what you would expect to find in a chanegelog. It should provide a summary of that specific release.

An approach that seems to work well in other repositories is to have the creation of the GitHub release and its text (and associated Git tag) as a manual task, but then to have a GitHub Actions workflow triggered by the new tag drive any automated release pipeline.

**Comment by SamYuan1990** [comment]
> I don't think this is a good idea. The README should provide information for people coming to the repository, not anything specific to a particular release version. The text for a GitHub release is more what you would expect to find in a chanegelog. It should provide a summary of that specific release.
> 
> An approach that seems to work well in other repositories is to have the creation of the GitHub release and its text (and associated Git tag) as a manual task, but then to have a GitHub Actions workflow triggered by the new tag drive any automated release pipeline.

@bestbeforetoday , so we will ref https://github.com/hyperledger/fabric to have tag to document link and release pages? or https://github.com/hyperledger/fabric-sdk-go#retired-versions

**Comment by bestbeforetoday** [comment]
I would suggest creating a [GitHub release](https://github.com/hyperledger/fabric-admin-sdk/releases) using the GitHub Web UI when you want to publish a release version. Here you can add the release notes for the release, and it will also create a Git tag for you. Any automated processes you want to run as part of that release can be triggered by the tag in a GitHub Actions workflow, like how Fabric does [here](https://github.com/hyperledger/fabric/blob/52b9f467531c442ce21d855b97f4fc2ac3fa50f3/.github/workflows/release.yml#L7-L9) (although you might want to use `v**` as the tag name to trigger from any tag starting with a `v`).

**Comment by SamYuan1990** [comment]
ok, let's close this one and use github web ui

**Pull request closed without merging**
