### PR TITLE
Nominate channing duan

### PR DESCRIPTION
**Pull request by SamYuan1990**
Nominate @channingduan as maintainer for this project.

duan helps with init features of golang code.

ref to https://github.com/hyperledger/fabric-admin-sdk/pulls?q=is%3Apr+is%3Aclosed+author%3Achanningduan

Signed-off-by: Sam Yuan <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
fix #74 70

**Review by bestbeforetoday — CHANGES_REQUESTED** [review]
The list should be sorted in some way. It is currently sorted alphabetically (by first name), which would mean that Channing would go at the top of the list. Or you could choose an alternative sorting and re-order all the entries to match that

**Comment by SamYuan1990** [comment]
> The list should be sorted in some way. It is currently sorted alphabetically (by first name), which would mean that Channing would go at the top of the list. Or you could choose an alternative sorting and re-order all the entries to match that

ok , it sorted by alphabetically for now.

**Review by bestbeforetoday — APPROVED** [review]
Looks good to me. We'll also need to raise an issue with Hyperledger to have Channing added to the @hyperledger/fabric-admin-sdk-maintainers team:

https://github.com/hyperledger/governance/issues/new/choose

**Review by bestbeforetoday — APPROVED** [review]

**Comment by SamYuan1990** [comment]
> Looks good to me. We'll also need to raise an issue with Hyperledger to have Channing added to the @hyperledger/fabric-admin-sdk-maintainers team:
> 
> https://github.com/hyperledger/governance/issues/new/choose

I think once @davidkhala gives his approval and merged this PR. We can raise an issue with Hyperledger to have Channing added to the @hyperledger/fabric-admin-sdk-maintainers team.

**Comment by davidkhala** [comment]
I prefer use personal than company email for contribution.

**Review by bestbeforetoday — APPROVED** [review]

**Pull request merged**
